//---------------------------------------------------------------------------------------------------------------------------------------------------------------
            //peliculas
###
GET http://localhost:3000/user/getallusers

###
GET http://localhost:3000/user/getByUsername/luisa

###
GET http://localhost:3000/user/deleteUser/65175a9b01c4049b43a753bd

###
PUT http://localhost:3000/user/update/65175a9b01c4049b43a753bd 
Content-Type:  application/json

{
"username":"luisa", 
"email":"hola@gmail.com", 
"name":"luisa", 
"password":"pepe"
}

###
POST http://localhost:3000/user/register
Content-Type:  application/json

{
"username":"luisa", 
"email":"hola@gmail.com", 
"name":"luisa", 
"password":"pepe"
}
//---------------------------------------------------------------------------------------------------------------------------------------------------------------
            //pokemon

###
POST http://localhost:3000/peliculas/register
Content-Type:  application/json

{
    "name": "fight",
    "lastname": "club",
    "year": "1999",
    "type": "accion"
}
###
GET http://localhost:3000/peliculas/getallpeli
###
GET http://localhost:3000/peliculas/getByName/

###
GET http://localhost:3000/peliculas/deletePeli/

###
PUT http://localhost:3000/peliculas/update/
Content-Type:  application/json

{
    "name": "fight",
    "lastname": "club",
    "year": "1999",
    "type": "accion"
}