//---------------------------------------------------------------------------------------------------------------------------------------------------------------
            //peliculas

###
POST http://localhost:3000/peliculas/register
Content-Type:  application/json

{
    "name": "",
    "year": "",
    "type": ""
}
###
GET http://localhost:3000/peliculas/getallpelis

###
GET http://localhost:3000/peliculas/getByName/nope

###
DELETE http://localhost:3000/peliculas/deletePeli/65291efe9cc37f22a8dce93a

###
PUT http://localhost:3000/peliculas/update/651b839dca4836b1f04c3531
Content-Type:  application/json

{
    "name": "Forest gump",
    "year": "1995",
    "type": "terror"
}